:     ___    ____  __    ___   _________
:    /   |  / _  |/ /   / / | / /__  __/           Source Code Static Analyzer
:   / /| | / / / / /   / /  |/ /  / /                   AdLint - Advanced Lint
:  / __  |/ /_/ / /___/ / /|  /  / /
: /_/  |_|_____/_____/_/_/ |_/  /_/   Copyright (C) 2010-2014, OGIS-RI Co.,Ltd.
:
: MS-Windows BAT file generated by adlintize 3.2.14 at 2021-10-17 00:46:03 +0900

adlint -v -t adlint_traits.yml -o . -p 1 -l adlint_files.txt
